#!/usr/bin/env python3
"""Insertion-certificate distribution on MetaQA (AGENTS.md P5).

Per query, competitors are the type-consistent siblings (other objects of the
gold answer's final relation) present in the anchor's k-hop subgraph. Reports
the distribution of the insertion budget b_ins and how it compares to the
deletion certificate k. CPU-only.

    uv run python scripts/compute_insertion_certificates.py \\
        --dataset metaqa-2hop --split dev --limit 2000
"""

import argparse
import json
from collections import Counter
from pathlib import Path

from mcgr.certify import insertion_certificate, query_certificate
from mcgr.data import load_dataset
from mcgr.kg.graph_store import khop_subgraph
from mcgr.kg.metaqa_kg import metaqa_graph
from mcgr.retrieval.evidence import metaqa_pair_index, metaqa_relation_objects, path_evidence

REPO_ROOT = Path(__file__).resolve().parents[1]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dataset", default="metaqa-2hop")
    ap.add_argument("--split", default="dev")
    ap.add_argument("--limit", type=int, default=2000)
    ap.add_argument("--max-competitors", type=int, default=200)
    ap.add_argument("--out", type=Path, default=REPO_ROOT / "results" / "insertion_certificate.md")
    args = ap.parse_args()
    hops = int(args.dataset.removeprefix("metaqa-").removesuffix("hop"))

    graph = metaqa_graph()
    pair_index = metaqa_pair_index()
    rel_objects = metaqa_relation_objects()

    b_dist: Counter[int] = Counter()
    k_dist: Counter[int] = Counter()
    n = tighter = 0
    for i, r in enumerate(load_dataset(args.dataset, args.split)):
        if i >= args.limit:
            break
        anchors = list(r.anchor_entities)
        if not anchors:
            continue
        answer = r.answers[0]
        sub = khop_subgraph(graph, anchors, hops)
        ev = path_evidence(sub, anchors[0], answer, pair_index)
        if not ev:
            continue
        rels = [rr for _s, rr, o in ev if o == answer]
        rel = rels[0] if rels else None
        present = set(sub.nodes())
        competitors = [o for o in rel_objects.get(rel, ()) if o in present and o not in r.answers][
            : args.max_competitors
        ]
        k = query_certificate(sub, anchors, answer)
        b = insertion_certificate(sub, anchors, answer, competitors)
        n += 1
        k_dist[k] += 1
        b_dist[b] += 1
        tighter += b < k

    def frac_ge1(d):
        return sum(v for kk, v in d.items() if kk >= 1) / n if n else 0

    lines = [
        "# Insertion-aware certificate — MetaQA (P5)",
        "",
        f"Generated by `scripts/compute_insertion_certificates.py` on {args.dataset}",
        f"{args.split} (n={n}). Competitors = type-consistent siblings under the gold",
        "answer's final relation, present in the anchor subgraph. See",
        "`threat_model.md` for the conservative assumptions (A1-A3).",
        "",
        "`b_ins = paths(answer) - max competitor paths - 1`; a forged competitor",
        "cannot reach the true answer's support with <= b_ins inserted triples.",
        "",
        f"- insertion-certified (b_ins >= 1): **{frac_ge1(b_dist):.1%}**",
        f"- deletion-certified (k >= 1): {frac_ge1(k_dist):.1%}",
        f"- b_ins strictly below k (a real competitor exists): {tighter / n:.1%} of queries"
        if n
        else "",
        "",
        f"b_ins distribution: {dict(sorted(b_dist.items())[:12])}",
        "",
        f"k distribution: {dict(sorted(k_dist.items())[:12])}",
        "",
        "The insertion certificate is never more permissive than deletion and is",
        "strictly tighter whenever a competing answer has genuine support — it is",
        "not a relabelling of k (threat_model.md §5).",
        "",
    ]
    args.out.write_text("\n".join(lines))
    print(json.dumps({"n": n, "b_ins_ge1": frac_ge1(b_dist), "k_ge1": frac_ge1(k_dist)}, indent=2))
    print(f"wrote {args.out.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
