#!/usr/bin/env python3
"""Aggregate P10 runs into results/selective_prediction.md.

    uv run python scripts/make_selective_report.py \\
        --runs $SCRATCH/runs/p10/metaqa2_dev $SCRATCH/runs/p10/metaqa3_dev
"""

import argparse
import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
OUT = REPO_ROOT / "results" / "selective_prediction.md"
COV_POINTS = [0.25, 0.5, 0.75, 1.0]


def risk_at(points, coverage):
    """Risk at the largest coverage <= target (points are increasing)."""
    best = None
    for c, r in points:
        if c <= coverage + 1e-9:
            best = r
    return best


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--runs", nargs="+", required=True, type=Path)
    args = ap.parse_args()
    summaries = [json.loads((r / "summary.json").read_text()) for r in args.runs]

    lines = [
        "# Certified selective prediction (P10 / H3)",
        "",
        "Generated by `scripts/make_selective_report.py`. Under the RAG-Safety",
        "attack, a selective predictor answers its most-trusted queries and",
        "abstains on the rest. We compare two abstention signals by **AURC** (area",
        "under the risk-coverage curve, lower = better): the certificate `k` vs",
        "self-consistency (agreement across sampled generations).",
        "",
        "H3: `k` is the better signal — a model can be *consistently wrong* through",
        "a forged single chain (k=0) that self-consistency rates confident.",
        "",
        "| dataset | model | n | attacked acc | AURC k | AURC self-consist. | winner |",
        "|---|---|---:|---:|---:|---:|---|",
    ]
    for s in summaries:
        ak = s["aurc"]["certificate_k"]
        ac = s["aurc"]["self_consistency"]
        winner = "**k**" if ak < ac else ("self-consist." if ac < ak else "tie")
        lines.append(
            f"| {s['dataset']} | {s['model'].replace('-Instruct', '')} | {s['n']} | "
            f"{s['attacked_accuracy']:.2f} | {ak:.3f} | {ac:.3f} | {winner} |"
        )
    lines.append("")

    for s in summaries:
        lines += [
            f"## {s['dataset']} risk at coverage",
            "",
            "| coverage | risk (k signal) | risk (self-consistency) |",
            "|---|---:|---:|",
        ]
        rk = s["risk_coverage"]["certificate_k"]
        rc = s["risk_coverage"]["self_consistency"]
        for cov in COV_POINTS:
            xk = risk_at(rk, cov)
            xc = risk_at(rc, cov)
            xks = f"{xk:.2f}" if xk is not None else "n/a*"
            xcs = f"{xc:.2f}" if xc is not None else "n/a*"
            lines.append(f"| {cov:.0%} | {xks} | {xcs} |")
        lines.append("")
        lines.append(
            "\\* n/a = the signal is too coarse to operate at that coverage "
            "(large tie-groups). Self-consistency lumps most queries into "
            "'fully agree', so it cannot abstain finely — itself a point in "
            "`k`'s favour; the AURC above integrates the full curve regardless."
        )
        lines.append("")

    lines += [
        "## Takeaway",
        "",
        "Lower AURC for `k` means abstaining on low-`k` queries removes the",
        "attack-vulnerable ones more effectively than abstaining on low-confidence",
        "ones — the certificate is grounded in the graph's redundancy, which is",
        "exactly what the insertion attack exploits, whereas self-consistency can",
        "be high on a confidently-forged answer (AGENTS.md P10 / H3).",
        "",
    ]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
