#!/usr/bin/env python3
"""Aggregate per-split certificate summaries into the P4 report.

Reads summary.json from each run dir under $SCRATCH/runs/certificates and
writes results/certificate_distribution.md. Reproducible:

    uv run python scripts/make_certificate_report.py
"""

import json
import os
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
OUT = REPO_ROOT / "results" / "certificate_distribution.md"

# (display, run-dir name) in report order
CELLS = [
    ("MetaQA 1-hop", "dev", "metaqa-1hop_dev"),
    ("MetaQA 1-hop", "test", "metaqa-1hop_test"),
    ("MetaQA 2-hop", "dev", "metaqa-2hop_dev"),
    ("MetaQA 2-hop", "test", "metaqa-2hop_test"),
    ("MetaQA 3-hop", "dev", "metaqa-3hop_dev"),
    ("MetaQA 3-hop", "test", "metaqa-3hop_test"),
]


def runs_root() -> Path:
    base = os.environ.get("MCGR_RUNS_ROOT")
    if base:
        return Path(base)
    scratch = os.environ["SCRATCH"]
    return Path(scratch) / "runs" / "certificates"


def load_summary(name: str) -> dict:
    return json.loads((runs_root() / name / "summary.json").read_text())


def fmt_hist(dist: dict[str, int], top: int = 10) -> str:
    items = sorted(((int(k), v) for k, v in dist.items()), key=lambda kv: kv[0])
    shown = items[:top]
    parts = [f"{k}:{v}" for k, v in shown]
    if len(items) > top:
        parts.append("…")
    return "{" + ", ".join(parts) + "}"


def main() -> int:
    summaries = {name: load_summary(name) for _, _, name in CELLS}
    lines = [
        "# Deletion-certificate distribution — MetaQA (P4)",
        "",
        "Full-split result. Generated by `scripts/make_certificate_report.py`",
        "from the Slurm sweep (`slurm/certify_metaqa.sbatch`); per-query rows in",
        "`$SCRATCH/runs/certificates/*/metrics.csv`.",
        "",
        "Certificate (AGENTS.md §7): `k = (#edge-disjoint anchor→answer paths in",
        "the anchor's k-hop subgraph) - 1`, on an undirected fact graph (deletion",
        "threat model). `k ≥ 1` = provably robust to deletion of ≥ 1 supporting",
        "triple; `k = 0` = single fragile chain; `k = -1` = unsupported. Modeling",
        "choices in `DECISIONS.md`.",
        "",
        "| Dataset | Split | N | frac k≥1 | frac supported | mean k (supported) |",
        "|---|---|---:|---:|---:|---:|",
    ]
    for display, split, name in CELLS:
        s = summaries[name]
        lines.append(
            f"| {display} | {split} | {s['n_queries']:,} | "
            f"{s['frac_k_ge_1']:.3f} | {s['frac_supported']:.3f} | "
            f"{s['mean_k_supported']:.2f} |"
        )

    lines += ["", "## k histograms", ""]
    for display, split, name in CELLS:
        lines.append(f"- **{display} / {split}**: {fmt_hist(summaries[name]['k_distribution'])}")

    lines += [
        "",
        "## The finding (H1)",
        "",
        "Certified redundancy rises sharply and monotonically with hop count, and",
        "is stable across dev/test:",
        "",
        f"- **1-hop → {summaries['metaqa-1hop_dev']['frac_k_ge_1']:.1%} certifiable.** "
        "A 1-hop answer is a single fact; there is essentially no independent second "
        "path, so `k = 0` almost everywhere. Also a correctness check.",
        f"- **2-hop → {summaries['metaqa-2hop_dev']['frac_k_ge_1']:.1%} "
        f"(dev) / {summaries['metaqa-2hop_test']['frac_k_ge_1']:.1%} (test).** "
        "A substantial minority of queries admit an independent second path.",
        f"- **3-hop → {summaries['metaqa-3hop_dev']['frac_k_ge_1']:.1%} "
        f"(dev) / {summaries['metaqa-3hop_test']['frac_k_ge_1']:.1%} (test).** "
        "Dense KB regions yield many edge-disjoint supporting paths.",
        "",
        "This monotonic hop-count → path-redundancy relationship, on full splits",
        "(~10k-15k queries each) with tight dev/test agreement, is the core P7",
        "signal and the empirical basis of the §12 hop-count vs path-count ablation.",
        "",
        "## Scope & caveats (AGENTS.md §1)",
        "",
        "- MetaQA only so far (self-contained KB, no Freebase / no gated model).",
        "  2WikiMultiHopQA (native gold triples) is the next KG to certify.",
        "- `k` counts *structural* edge-disjoint paths in the bounded k-hop",
        "  subgraph; paths inside the ball may exceed `hops` edges, so `k` partly",
        "  reflects local KB connectivity. Structural ≠ evidential independence",
        "  (P5) — two edge-disjoint paths can still share a corrupted source.",
        "- Certificate is conservative: parallel facts are collapsed to one edge,",
        "  which can only lower `k`.",
        "",
    ]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
