#!/usr/bin/env python3
"""Aggregate P7 gate runs into results/stage1_gate.md (AGENTS.md P7).

Reads summary.json from the given run dirs (one per attack budget), bins
queries by certificate k, and reports clean accuracy plus attack flip rate
per k-bin per budget. Prints a suggested GO/PIVOT read; the decision is
recorded by hand in DECISIONS.md.

    uv run python scripts/make_stage1_report.py \\
        --runs $SCRATCH/runs/p7/metaqa2_dev_b2 $SCRATCH/runs/p7/metaqa2_dev_b8
"""

import argparse
import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
OUT = REPO_ROOT / "results" / "stage1_gate.md"

# k bins for a stable signal
BINS = [(0, 0, "0"), (1, 2, "1-2"), (3, 5, "3-5"), (6, 10, "6-10"), (11, 10**9, "11+")]


def bin_label(k: int) -> str:
    for lo, hi, lab in BINS:
        if lo <= k <= hi:
            return lab
    return "?"


def binned(summary: dict) -> dict[str, dict]:
    agg: dict[str, dict] = {lab: {"n": 0, "clean_n": 0, "flips": 0} for *_, lab in BINS}
    for k_str, v in summary["per_k"].items():
        lab = bin_label(int(k_str))
        a = agg[lab]
        a["n"] += v["n"]
        a["clean_n"] += v["clean_correct_n"]
        # flip_rate is over clean-correct; recover the flip count
        if v["flip_rate"] is not None:
            a["flips"] += round(v["flip_rate"] * v["clean_correct_n"])
    return agg


def condition(summary: dict) -> str:
    model = summary["model"].replace("-Instruct", "")
    anon = ", anonymized" if summary.get("anonymized") else ""
    return f"{model}{anon}"


def k0_vs_certified(agg: dict[str, dict]) -> tuple[float | None, float | None]:
    """Flip rate for k=0 and for all certified (k>=1) bins."""
    k0 = agg["0"]
    cert = {"clean_n": 0, "flips": 0}
    for lab in ("1-2", "3-5", "6-10", "11+"):
        cert["clean_n"] += agg[lab]["clean_n"]
        cert["flips"] += agg[lab]["flips"]
    f0 = k0["flips"] / k0["clean_n"] if k0["clean_n"] else None
    fc = cert["flips"] / cert["clean_n"] if cert["clean_n"] else None
    return f0, fc


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--runs", nargs="+", required=True, type=Path)
    args = ap.parse_args()

    summaries = [json.loads((r / "summary.json").read_text()) for r in args.runs]
    summaries.sort(key=lambda s: (condition(s), s["budget"]))

    lines = [
        "# Stage-1 de-risk gate (P7) — certified k vs empirical robustness",
        "",
        "Generated by `scripts/make_stage1_report.py`. Tests H1: does the",
        "deletion certificate `k` predict robustness to the RAG-Safety insertion",
        "attack? For MetaQA 2-hop queries stratified by `k`, the reasoner answers",
        "from clean supporting evidence and from evidence + a forged competing",
        "chain to a type-consistent wrong answer. **Flip rate** = fraction of",
        "*clean-correct* queries whose answer flips to the forged wrong answer",
        "under attack. Prediction: flip rate falls as `k` rises (more independent",
        "real support resists a forged path).",
        "",
        "## Robustness of the effect (k=0 vs certified k>=1 flip rate)",
        "",
        "The gap holds across reasoner model and under entity anonymization (which",
        "removes parametric memory) — evidence the effect is graph-structural.",
        "",
        "| condition | budget | n | k=0 flip | k>=1 flip | gap (x) |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    for s in summaries:
        f0, fc = k0_vs_certified(binned(s))
        gap = f"{f0 / fc:.1f}x" if (f0 and fc) else "n/a"
        f0s = f"{f0:.2f}" if f0 is not None else "n/a"
        fcs = f"{fc:.2f}" if fc is not None else "n/a"
        lines.append(f"| {condition(s)} | {s['budget']} | {s['n']} | {f0s} | {fcs} | {gap} |")
    lines.append("")

    for s in summaries:
        agg = binned(s)
        lines += [
            f"## {condition(s)}, attack budget {s['budget']} (n={s['n']})",
            "",
            "| k bin | n | clean acc | flip rate |",
            "|---|---:|---:|---:|",
        ]
        for *_, lab in BINS:
            a = agg[lab]
            if a["n"] == 0:
                continue
            clean_acc = a["clean_n"] / a["n"] if a["n"] else 0
            flip = a["flips"] / a["clean_n"] if a["clean_n"] else None
            flip_s = f"{flip:.2f}" if flip is not None else "n/a"
            lines.append(f"| {lab} | {a['n']} | {clean_acc:.2f} | {flip_s} |")
        lines.append("")

    lines += [
        "## Decision",
        "",
        "GO if certified (k>=1) queries are markedly more robust than k=0 and a",
        "non-trivial fraction of queries admit k>=1 (certificate_distribution.md:",
        "MetaQA 2-hop 31%, 3-hop 97%, 2Wiki 68%). Otherwise PIVOT to the",
        "certificate-maximizing retriever (P8). Decision recorded in DECISIONS.md.",
        "",
    ]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
