#!/usr/bin/env python3
"""Generate results/data_stats.md: per-dataset counts and structure.

Reproducible: `uv run python scripts/make_data_stats.py`. Reads datasets
from $SCRATCH (or $MCGR_DATA_ROOT); writes the markdown table.
"""

from collections import Counter
from pathlib import Path

from mcgr.data import load_dataset

REPO_ROOT = Path(__file__).resolve().parents[1]
OUT = REPO_ROOT / "results" / "data_stats.md"

# (display name, loader name, splits to count)
DATASETS = [
    ("2WikiMultiHopQA", "2wikimultihopqa", ["train", "dev"]),
    ("MetaQA 1-hop", "metaqa-1hop", ["train", "dev", "test"]),
    ("MetaQA 2-hop", "metaqa-2hop", ["train", "dev", "test"]),
    ("MetaQA 3-hop", "metaqa-3hop", ["train", "dev", "test"]),
    ("MuSiQue", "musique", ["train", "dev"]),
    ("WebQSP", "webqsp", ["train", "test"]),
    ("CWQ", "cwq", ["train", "dev"]),
    ("HotpotQA", "hotpotqa", ["train", "validation"]),
]


def summarize(name: str, split: str) -> dict:
    n = 0
    with_gold = 0
    with_anchor = 0
    type_counts: Counter[str] = Counter()
    for r in load_dataset(name, split):
        n += 1
        with_gold += bool(r.gold_paths)
        with_anchor += bool(r.anchor_entities)
        t = r.meta.get("type") or r.meta.get("compositionality_type")
        if t:
            type_counts[t] += 1
    return {
        "n": n,
        "with_gold": with_gold,
        "with_anchor": with_anchor,
        "types": type_counts,
    }


def main() -> int:
    lines = [
        "# Dataset statistics",
        "",
        "Generated by `scripts/make_data_stats.py` from datasets on `$SCRATCH`.",
        "`gold%` = fraction of records carrying a triple-level gold path;",
        "`anchor%` = fraction with at least one anchor entity resolved by the loader.",
        "",
        "| Dataset | Split | Questions | gold% | anchor% |",
        "|---|---|---:|---:|---:|",
    ]
    type_notes = []
    for display, name, splits in DATASETS:
        for split in splits:
            s = summarize(name, split)
            n = s["n"]
            gold = f"{100 * s['with_gold'] / n:.0f}%" if n else "—"
            anch = f"{100 * s['with_anchor'] / n:.0f}%" if n else "—"
            lines.append(f"| {display} | {split} | {n:,} | {gold} | {anch} |")
            if s["types"]:
                top = ", ".join(f"{k}={v:,}" for k, v in s["types"].most_common(6))
                type_notes.append(f"- **{display} / {split}** question types: {top}")

    if type_notes:
        lines += ["", "## Question-type distributions", ""]
        lines += type_notes

    lines += [
        "",
        "## Caveats (AGENTS.md §1 empirical honesty)",
        "",
        "- **2WikiMultiHopQA** is the only dataset with native triple-level gold "
        "paths (`evidences`), hence the lead role (100% gold).",
        "- **MuSiQue** gold% (66%) reflects that only ~2/3 of decomposition hops "
        "use the structured `entity >> relation` template; the rest are "
        "natural-language sub-questions. The full raw decomposition is kept in "
        "`meta['decomposition']` for P2 KG construction.",
        "- **WebQSP / CWQ** have no loader-side gold paths or (CWQ) anchors: these "
        "are encoded in Freebase/SPARQL and materialized in P2 once the Freebase "
        "endpoint is available (§3.3, [HUMAN-REQUIRED]).",
        "- **MetaQA / HotpotQA** have anchors but no triple gold paths; MetaQA "
        "paths come from its self-contained KB, HotpotQA from text-constructed KGs "
        "(P2).",
        "- **WebQSP/CWQ dataset-quality caveat** (AGENTS.md §1, arXiv:2505.23495): "
        "cleaned-subset filtering is applied downstream, not at load time.",
        "",
    ]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
